import React, { useCallback, useEffect, useState } from 'react'
import { useAuth } from '../../contexts/AuthContext'
import { WorkLocation } from '../../types'
import { API_URL } from '../../src/config'

const LocationManager: React.FC = () => {
  const { apiFetch } = useAuth()
  const [locations, setLocations] = useState<WorkLocation[]>([])
  const [name, setName] = useState(''); const [latitude, setLatitude] = useState(''); const [longitude, setLongitude] = useState(''); const [radius, setRadius] = useState('100')
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const refresh = useCallback(async () => { const response = await apiFetch(`${API_URL}/locations`); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Unable to load locations.'); setLocations(data) }, [apiFetch])
  useEffect(() => { void refresh().catch(error => setError(error.message)) }, [refresh])
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const response = await apiFetch(`${API_URL}/locations`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, latitude: Number(latitude), longitude: Number(longitude), radius: Number(radius) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Unable to add the location.'); setName(''); setLatitude(''); setLongitude(''); setRadius('100'); await refresh() } catch (error) { setError(error instanceof Error ? error.message : 'Unable to add the location.') } finally { setLoading(false) } }
  const retire = async (id: number) => { if (!window.confirm('Retire this location? Existing attendance records will remain available.')) return; try { const response = await apiFetch(`${API_URL}/locations/${id}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Unable to retire the location.'); await refresh() } catch (error) { setError(error instanceof Error ? error.message : 'Unable to retire the location.') } }
  return <div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><div className="bg-white dark:bg-slate-800 p-6 rounded-lg shadow-md"><h3 className="text-xl font-semibold mb-4">Add work location</h3>{error && <p className="bg-red-100 text-red-700 p-3 rounded-lg mb-4">{error}</p>}<form onSubmit={submit}><input value={name} onChange={event => setName(event.target.value)} required placeholder="Location name" className="w-full px-4 py-2 border rounded-lg mb-3" /><input type="number" value={radius} onChange={event => setRadius(event.target.value)} required placeholder="Radius (meters)" className="w-full px-4 py-2 border rounded-lg mb-3" /><input type="number" step="any" value={latitude} onChange={event => setLatitude(event.target.value)} required placeholder="Latitude" className="w-full px-4 py-2 border rounded-lg mb-3" /><input type="number" step="any" value={longitude} onChange={event => setLongitude(event.target.value)} required placeholder="Longitude" className="w-full px-4 py-2 border rounded-lg mb-4" /><button disabled={loading} className="w-full bg-indigo-600 text-white py-2 rounded-lg disabled:bg-indigo-400">{loading ? 'Adding…' : 'Add location'}</button></form></div><div className="bg-white dark:bg-slate-800 p-6 rounded-lg shadow-md"><h3 className="text-xl font-semibold mb-4">Allowed locations</h3><ul className="space-y-3">{locations.map(location => <li key={location.id} className="flex justify-between items-center p-3 bg-slate-100 dark:bg-slate-700 rounded-md"><span>{location.name} · {location.radius}m</span><button onClick={() => retire(location.id)} className="text-red-500">Retire</button></li>)}{!locations.length && <li className="text-slate-500">No locations defined.</li>}</ul></div></div>
}
export default LocationManager
