const test = require('node:test');
const assert = require('node:assert/strict');
const { createAttendanceController } = require('../../controllers/attendanceController');
const { hash } = require('../../lib/http');
test('attendance controller returns already-decoded JSONB replay without parsing it', async () => {
  const sample = { latitude: 25, longitude: 55, locationId: 1, accuracy: null };
  const fingerprint = hash(JSON.stringify({ action: 'check-in', ...sample, attendanceId: null }));
  const body = { message: 'Checked in successfully.', attendance: { id: 1 } };
  const store = { transaction: fn => fn({ get: async sql => sql.includes('FROM users') ? { id: 1 } : { request_hash: fingerprint, response_json: body, status_code: 201 } }) };
  const controller = createAttendanceController({ store });
  let replayed = false;
  const response = { set: () => { replayed = true; }, status(code) { assert.equal(code, 201); return this; }, json(value) { assert.equal(value, body); } };
  await controller.checkIn({ body: { latitude: 25, longitude: 55, locationId: 1 }, user: { id: 1, company_id: 1 }, get: () => 'replay_request_123456' }, response);
  assert.equal(replayed, true);
});
const request = require('supertest');
const crypto = require('node:crypto');
const { createApp } = require('../../app');
const { createAuth } = require('../../middleware/authMiddleware');
const { loadConfig } = require('../../config');
test('session protocol restores, requires CSRF, revokes logout, rejects expiry and rechecks user state', async () => {
  const config = loadConfig({ JWT_SECRET: crypto.randomBytes(32).toString('hex'), OUTBOX_ENCRYPTION_KEY: crypto.randomBytes(32).toString('base64') });
  let instant = new Date(), active = true, revoked = false;
  const user = { id: 1, role: 'employee', company_id: 1, name: 'Protocol fixture', email: 'protocol@example.invalid' };
  const tx = { get: async () => active && !revoked ? user : undefined, run: async sql => { if (sql.startsWith('UPDATE sessions')) revoked = true; } };
  const store = { read: fn => fn(tx), transaction: fn => fn(tx) };
  const now = () => instant;
  const auth = createAuth({ store, config, now });
  const session = await auth.loginSession(tx, user, instant);
  const app = createApp({ store, config, now });
  const cookie = 'attend_session=' + session.token;
  await request(app).get('/api/auth/session').set('Cookie', cookie).expect(200);
  await request(app).post('/api/auth/logout').set('Cookie', cookie).expect(403);
  active = false;
  await request(app).get('/api/auth/session').set('Cookie', cookie).expect(401);
  active = true;
  await request(app).post('/api/auth/logout').set('Cookie', cookie).set('X-CSRF-Token', session.csrfToken).expect(200);
  await request(app).get('/api/auth/session').set('Cookie', cookie).expect(401);
  revoked = false; instant = new Date(instant.getTime() + config.sessionMs + 1000);
  await request(app).get('/api/auth/session').set('Cookie', cookie).expect(401);
});
