-- Attend - PostgreSQL initial schema
-- Fresh database. No legacy SQLite data is migrated.

BEGIN;

-- =========================================================
-- 1. Companies
-- =========================================================

CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    owner_id BIGINT,
    logo_url TEXT,
    timezone TEXT NOT NULL DEFAULT 'UTC',
    timezone_configured BOOLEAN NOT NULL DEFAULT FALSE
);

-- =========================================================
-- 2. Users
-- =========================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_id TEXT,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    normalized_email TEXT NOT NULL,
    password TEXT,
    role TEXT NOT NULL DEFAULT 'employee',
    company_id BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    invited_at TIMESTAMPTZ,
    activated_at TIMESTAMPTZ,
    archived_at TIMESTAMPTZ,

    CONSTRAINT users_role_check
        CHECK (role IN ('admin', 'manager', 'employee')),

    CONSTRAINT users_company_fk
        FOREIGN KEY (company_id)
        REFERENCES companies(id)
);

-- Company owner points to the user who owns the company.
ALTER TABLE companies
ADD CONSTRAINT companies_owner_fk
FOREIGN KEY (owner_id)
REFERENCES users(id);

-- =========================================================
-- 3. Locations
-- =========================================================

CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    radius INTEGER NOT NULL,
    retired_at TIMESTAMPTZ,

    CONSTRAINT locations_company_fk
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT locations_latitude_check
        CHECK (latitude BETWEEN -90 AND 90),

    CONSTRAINT locations_longitude_check
        CHECK (longitude BETWEEN -180 AND 180),

    CONSTRAINT locations_radius_check
        CHECK (radius > 0)
);

-- =========================================================
-- 4. Attendance
-- =========================================================

CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    location_id BIGINT,

    check_in_time TIMESTAMPTZ NOT NULL,
    check_out_time TIMESTAMPTZ,

    check_in_latitude DOUBLE PRECISION NOT NULL,
    check_in_longitude DOUBLE PRECISION NOT NULL,

    check_out_latitude DOUBLE PRECISION,
    check_out_longitude DOUBLE PRECISION,

    CONSTRAINT attendance_employee_fk
        FOREIGN KEY (employee_id)
        REFERENCES users(id),

    CONSTRAINT attendance_company_fk
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT attendance_location_fk
        FOREIGN KEY (location_id)
        REFERENCES locations(id),

    CONSTRAINT attendance_check_in_latitude_check
        CHECK (check_in_latitude BETWEEN -90 AND 90),

    CONSTRAINT attendance_check_in_longitude_check
        CHECK (check_in_longitude BETWEEN -180 AND 180),

    CONSTRAINT attendance_check_out_latitude_check
        CHECK (
            check_out_latitude IS NULL
            OR check_out_latitude BETWEEN -90 AND 90
        ),

    CONSTRAINT attendance_check_out_longitude_check
        CHECK (
            check_out_longitude IS NULL
            OR check_out_longitude BETWEEN -180 AND 180
        ),

    CONSTRAINT attendance_checkout_after_checkin
        CHECK (
            check_out_time IS NULL
            OR check_out_time >= check_in_time
        )
);

-- Only one open attendance record per employee.
CREATE UNIQUE INDEX attendance_one_open
ON attendance(employee_id)
WHERE check_out_time IS NULL;

-- =========================================================
-- 5. Sessions
-- =========================================================

CREATE TABLE sessions (
    token_hash TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,

    CONSTRAINT sessions_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);

-- =========================================================
-- 6. Invitations
-- =========================================================

CREATE TABLE invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    company_id BIGINT,
    token_hash TEXT NOT NULL UNIQUE,
    kind TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_by BIGINT,

    CONSTRAINT invitations_kind_check
        CHECK (
            kind IN (
                'invitation',
                'activation',
                'password_reset'
            )
        ),

    CONSTRAINT invitations_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT invitations_company_fk
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT invitations_created_by_fk
        FOREIGN KEY (created_by)
        REFERENCES users(id)
);

CREATE UNIQUE INDEX invitations_one_pending
ON invitations(user_id, kind)
WHERE consumed_at IS NULL
  AND revoked_at IS NULL;

-- =========================================================
-- 7. Audit Events
-- =========================================================

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT,
    actor_id BIGINT,
    subject_id BIGINT,
    event_type TEXT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    details_json JSONB NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT audit_company_fk
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT audit_actor_fk
        FOREIGN KEY (actor_id)
        REFERENCES users(id),

    CONSTRAINT audit_subject_fk
        FOREIGN KEY (subject_id)
        REFERENCES users(id)
);

-- Audit events are append-only.
CREATE OR REPLACE FUNCTION prevent_audit_event_changes()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'audit events are append-only';
END;
$$;

CREATE TRIGGER audit_events_no_update
BEFORE UPDATE ON audit_events
FOR EACH ROW
EXECUTE FUNCTION prevent_audit_event_changes();

CREATE TRIGGER audit_events_no_delete
BEFORE DELETE ON audit_events
FOR EACH ROW
EXECUTE FUNCTION prevent_audit_event_changes();

-- =========================================================
-- 8. Attendance Requests / Idempotency
-- =========================================================

CREATE TABLE attendance_requests (
    company_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    request_key TEXT NOT NULL,
    request_hash TEXT NOT NULL,
    response_json JSONB NOT NULL,
    status_code INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (company_id, user_id, request_key),

    CONSTRAINT attendance_requests_company_fk
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT attendance_requests_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);

-- =========================================================
-- 9. Email Outbox
-- =========================================================

CREATE TABLE email_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key TEXT NOT NULL UNIQUE,
    company_id BIGINT,
    invitation_id BIGINT,
    kind TEXT NOT NULL,
    payload_encrypted TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    next_attempt_at TIMESTAMPTZ NOT NULL,
    locked_until TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    last_error TEXT,

    CONSTRAINT email_outbox_status_check
        CHECK (
            status IN (
                'pending',
                'sending',
                'sent',
                'failed',
                'cancelled'
            )
        ),

    CONSTRAINT email_outbox_company_fk
        FOREIGN KEY (company_id)
        REFERENCES companies(id),

    CONSTRAINT email_outbox_invitation_fk
        FOREIGN KEY (invitation_id)
        REFERENCES invitations(id)
);

-- =========================================================
-- Indexes
-- =========================================================

CREATE UNIQUE INDEX users_normalized_email_unique
ON users(normalized_email);

CREATE UNIQUE INDEX users_google_id_unique
ON users(google_id)
WHERE google_id IS NOT NULL;

CREATE INDEX users_company_role
ON users(company_id, role, archived_at, is_active);

CREATE INDEX locations_company
ON locations(company_id, retired_at);

CREATE INDEX attendance_employee_time
ON attendance(employee_id, check_in_time DESC, id DESC);

CREATE INDEX attendance_company_time
ON attendance(company_id, check_in_time DESC, id DESC);

CREATE INDEX attendance_company_checkout
ON attendance(company_id, check_out_time);

CREATE INDEX sessions_user
ON sessions(user_id, revoked_at);

CREATE INDEX invitations_company_pending
ON invitations(company_id, consumed_at, revoked_at, expires_at);

CREATE INDEX audit_company_time
ON audit_events(company_id, occurred_at DESC, id DESC);

CREATE INDEX email_outbox_ready
ON email_outbox(status, next_attempt_at, locked_until);

CREATE INDEX email_outbox_company
ON email_outbox(company_id, status);

COMMIT;